/* Spike O — stub packer, --lang rust mode.
 *
 * Implements ADR-0088's Phase 1 (Transform) for Rust carts.  For the spike,
 * the packer hardcodes constant values that match the toy cart's
 * cart.build.yaml declarations rather than parsing the manifest.
 *
 * Usage:
 *   stub_packer_rust --lang rust --out <OUT_DIR> --cart <cart.build.yaml>
 *
 * Output files written to OUT_DIR/:
 *   resources.rs — pub const R_HERO, V_SFX as ResourceHandle
 *   state.rs     — pub const S_CTR as FieldHandle<MainBuffer>
 *   handlers.rs  — pub const HANDLER_AI as HandlerHandle
 *
 * The fully-qualified type paths match the blyt32 SDK crate layout so that
 * `include!(concat!(env!("OUT_DIR"), "/resources.rs"))` works inside a
 * cart module that does `use blyt32::*`.  The generated files reference
 * types via `blyt32::` prefix to avoid ambiguity in the include! expansion.
 *
 * Cargo incremental-build integration:
 *   The cart's build.rs prints:
 *     cargo:rerun-if-changed=cart.build.yaml
 *     cargo:rerun-if-changed=build.rs
 *   so Cargo re-runs this packer only when those files change, not on
 *   every `cargo build`.  The Stage 4 incremental-build gate validates
 *   this: a no-change second invocation must not touch the output files.
 *
 * Hardcoded constants (spike-era; production packer parses cart.build.yaml):
 *   R_HERO  = ResourceHandle(1)   — hero sprite
 *   V_SFX   = ResourceHandle(2)   — sound effect
 *   S_CTR   = FieldHandle<MainBuffer>::new(0x00010001)
 *   HANDLER_AI = HandlerHandle(1)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void usage(const char *prog) {
    fprintf(stderr, "Usage: %s --lang rust --out <OUT_DIR> --cart <manifest>\n", prog);
    exit(1);
}

static int write_file(const char *dir, const char *name, const char *content) {
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s", dir, name);
    FILE *f = fopen(path, "w");
    if (!f) {
        perror(path);
        return 1;
    }
    fputs(content, f);
    fclose(f);
    return 0;
}

int main(int argc, char **argv) {
    const char *lang    = NULL;
    const char *out_dir = NULL;
    const char *cart    = NULL;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--lang") == 0 && i + 1 < argc)
            lang = argv[++i];
        else if (strcmp(argv[i], "--out") == 0 && i + 1 < argc)
            out_dir = argv[++i];
        else if (strcmp(argv[i], "--cart") == 0 && i + 1 < argc)
            cart = argv[++i];
        else
            usage(argv[0]);
    }

    if (!lang || !out_dir || !cart) usage(argv[0]);
    if (strcmp(lang, "rust") != 0) {
        fprintf(stderr, "error: unsupported --lang %s (only 'rust' is implemented)\n", lang);
        return 1;
    }

    /* resources.rs — image and audio resource handles */
    if (write_file(out_dir, "resources.rs",
        "// Generated by stub_packer_rust — do not edit.\n"
        "// Source: cart.build.yaml resources section.\n"
        "pub const R_HERO: blyt32::ResourceHandle = blyt32::ResourceHandle(1);\n"
        "pub const V_SFX:  blyt32::ResourceHandle = blyt32::ResourceHandle(2);\n"
    )) return 1;

    /* state.rs — typed field handles */
    if (write_file(out_dir, "state.rs",
        "// Generated by stub_packer_rust — do not edit.\n"
        "// Source: cart.build.yaml state_buffers section.\n"
        "// Raw field handle encoding: high 16 bits = buffer ID, low 16 bits = field index.\n"
        "pub const S_CTR: blyt32::buffers::FieldHandle<blyt32::buffers::MainBuffer>\n"
        "    = blyt32::buffers::FieldHandle::new(0x00010001);\n"
    )) return 1;

    /* handlers.rs — AI handler handles */
    if (write_file(out_dir, "handlers.rs",
        "// Generated by stub_packer_rust — do not edit.\n"
        "// Source: cart.build.yaml handlers section.\n"
        "pub const HANDLER_AI: blyt32::HandlerHandle = blyt32::HandlerHandle(1);\n"
    )) return 1;

    fprintf(stderr, "stub_packer_rust: wrote resources.rs state.rs handlers.rs to %s\n", out_dir);
    (void)cart; /* spike: cart.build.yaml is not parsed; constants are hardcoded */
    return 0;
}
