#!/usr/bin/env bash
# derive_allowlist.sh — Stage 3: strace-based ILP32 syscall allowlist derivation.
#
# Run INSIDE the Fedora 42 RISC-V QEMU guest with rv32emu and the cart
# workload binaries available.
#
# Usage:
#   derive_allowlist.sh <cart_dir>
#
# Where <cart_dir> contains the .blyt cart bundles from Spikes I, O, Q:
#   spike-i-case-a.blyt   (native C cart)
#   spike-i-case-b.blyt   (Lua cart)
#   spike-o-cart.blyt     (Rust cart)
#   spike-q-cart.blyt     (Lua+Rust hybrid)
#
# Outputs:
#   strace_*.txt           raw strace captures (one per workload)
#   syscall_union.txt      union of all syscall names
#   syscall_lp64.txt       LP64 syscalls only (rv32emu host process)
#   syscall_ilp32.txt      ILP32 compat syscalls (cart via compat layer)
#   allowlist_suggestion.h suggested C header for seccomp_allowlist.h update
#
# After reviewing allowlist_suggestion.h, update seccomp_allowlist.h manually.
#
# Prerequisites:
#   rv32emu must be on PATH or set RV32EMU=/path/to/rv32emu
#   strace must be installed (dnf install strace)

set -uo pipefail

CART_DIR="${1:-}"
if [ -z "$CART_DIR" ]; then
    echo "usage: $0 <cart_dir>" >&2
    exit 1
fi

RV32EMU="${RV32EMU:-rv32emu}"
OUT_DIR="${2:-$(pwd)/strace-out}"
mkdir -p "$OUT_DIR"

if ! command -v "$RV32EMU" &>/dev/null; then
    echo "rv32emu not found (set RV32EMU=/path/to/rv32emu)" >&2
    exit 1
fi

if ! command -v strace &>/dev/null; then
    echo "strace not found (dnf install strace)" >&2
    exit 1
fi

# RV32EMU commit for allowlist annotation.
RV32EMU_VER=$("$RV32EMU" --version 2>&1 | head -1 || echo "unknown")
echo "rv32emu: $RV32EMU_VER"
echo "cart_dir: $CART_DIR"
echo "output: $OUT_DIR"

# Strace options:
#   -f: follow forks (rv32emu may fork for some carts)
#   -e trace=all: capture all syscalls
#   -v: verbose (don't abbreviate structs — not needed here, omit for speed)
#   -T: show time spent (useful for profiling; omit for pure syscall capture)
STRACE_OPTS="-f -e trace=all -o"

STRACE_DURATION=3   # seconds; enough for 60fps × 3s = 180 frames minimum

declare -A WORKLOADS=(
    ["native_c"]="spike-i-case-a.blyt"
    ["lua"]="spike-i-case-b.blyt"
    ["rust"]="spike-o-cart.blyt"
    ["lua_rust"]="spike-q-cart.blyt"
)

echo ""
echo "=== Stage 3: strace over cart workloads ==="

FOUND_ANY=0
for name in "${!WORKLOADS[@]}"; do
    cart="${CART_DIR}/${WORKLOADS[$name]}"
    out="$OUT_DIR/strace_${name}.txt"
    if [ ! -f "$cart" ]; then
        echo "  SKIP $name: $cart not found"
        continue
    fi
    FOUND_ANY=1
    echo "  strace $name (${STRACE_DURATION}s)..."
    timeout "$STRACE_DURATION" strace $STRACE_OPTS "$out" "$RV32EMU" "$cart" \
        >/dev/null 2>&1 || true
    LINES=$(wc -l < "$out" 2>/dev/null || echo 0)
    echo "  → $out ($LINES strace lines)"
done

if [ "$FOUND_ANY" -eq 0 ]; then
    echo "No cart workloads found in $CART_DIR — cannot derive allowlist."
    echo "Expected files: spike-i-case-a.blyt, spike-i-case-b.blyt,"
    echo "                spike-o-cart.blyt, spike-q-cart.blyt"
    exit 1
fi

# Collect all unique syscall names from strace output.
# strace format: "<pid> <syscall>(<args>) = <ret>"
echo ""
echo "=== Collecting syscall names ==="

UNION="$OUT_DIR/syscall_union.txt"
grep -h '^[0-9]* \+[a-z_0-9]\+(' "$OUT_DIR"/strace_*.txt 2>/dev/null \
    | sed 's/^[0-9 ]*//; s/(.*$//' \
    | sort -u > "$UNION"
echo "Unique syscall names: $(wc -l < "$UNION")"
cat "$UNION"

# Separate LP64 and ILP32 syscalls.
# ILP32 compat syscalls have distinct numbers:
#   - mmap2 (192), fstat64 (325), fstatat64 (327), clock_gettime64 (403),
#     futex_time64 (422)
# Use syscall number cross-reference to classify.
# For the spike: we conservatively include all observed syscalls in the ILP32
# list (since rv32emu uses the host LP64 syscall path; the compat layer syscalls
# are the ones the CART makes, visible with PID filtering from strace -f).
#
# Manual review required: check which PIDs correspond to rv32emu (LP64) vs
# the RV32 cart process (ILP32 compat layer).  The cart's PID appears after
# rv32emu forks/clones a child to execute the RV32 binary.

echo ""
echo "=== Stage 3 note ==="
echo "Review strace output manually:"
echo "  - Parent PID = rv32emu LP64 process (host syscalls)"
echo "  - Child PID(s) = RV32 cart via compat layer (ILP32 syscalls)"
echo ""
echo "Cross-reference syscall names with numbers:"
echo "  LP64/ILP32 shared: check asm-generic/unistd.h"
echo "  ILP32-specific: mmap2=192, fstat64=325, fstatat64=327,"
echo "                  clock_gettime64=403, futex_time64=422"
echo "  RISC-V arch-specific: riscv_flush_icache=258,259"

# Generate a C header suggestion from the union syscall list.
SUGG="$OUT_DIR/allowlist_suggestion.h"
{
    echo "/* allowlist_suggestion.h — Stage 3 output."
    echo " * Generated by derive_allowlist.sh from strace capture."
    echo " * rv32emu: $RV32EMU_VER"
    echo " * Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo " *"
    echo " * MANUAL REVIEW REQUIRED:"
    echo " *   1. Separate LP64 (rv32emu host) from ILP32 (cart compat) syscalls."
    echo " *   2. Remove syscalls only needed by rv32emu LP64 path (not cart)."
    echo " *   3. Remove syscalls already prevented by namespaces (socket, open)."
    echo " *   4. Add the resulting ILP32 list to seccomp_ilp32_nrs[] in"
    echo " *      spikes/spike-r/seccomp_allowlist.h."
    echo " */"
    echo ""
    echo "/* Union of all observed syscalls (LP64 + ILP32; manual separation needed):"
    while IFS= read -r name; do
        printf " *   %s\n" "$name"
    done < "$UNION"
    echo " */"
} > "$SUGG"
echo ""
echo "Suggestion header: $SUGG"
echo ""
echo "=== Stage 3: strace capture complete ==="
echo "Next: review strace files, update seccomp_allowlist.h, re-run Stage 2."
