// Typed state-buffer field handles.  FieldHandle<B> is parameterised on the
// buffer marker type B so the compiler rejects cross-buffer field accesses at
// compile time (ADR-0108 §4.2).
//
// Buffer is a sealed trait: cart code can *use* Buffer types but cannot
// implement Buffer outside this crate, preventing accidental handle aliasing.

use core::marker::PhantomData;
use crate::handles::Slot;
use crate::ffi;

mod private {
    pub trait Sealed {}
}

pub trait Buffer: private::Sealed {}

/// Zero-sized marker for the cart's primary state buffer.  Generated by the
/// stub packer into $OUT_DIR/state.rs; carts reference it by name.
pub struct MainBuffer;
impl private::Sealed for MainBuffer {}
impl Buffer for MainBuffer {}

/// Zero-sized marker used by the guard_wrong_buffer compile-fail test only.
pub struct EnemiesBuffer;
impl private::Sealed for EnemiesBuffer {}
impl Buffer for EnemiesBuffer {}

/// Typed field handle.  B is the buffer this handle belongs to; passing a
/// FieldHandle<MainBuffer> to a method that expects FieldHandle<EnemiesBuffer>
/// is a compile-time type error.
///
/// PhantomData<B> makes FieldHandle<B> covariant in B.  For the spike's
/// concrete zero-sized marker types (no lifetime parameters) this is safe.
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct FieldHandle<B: Buffer>(pub u32, PhantomData<B>);

impl<B: Buffer> FieldHandle<B> {
    pub const fn new(raw: u32) -> Self {
        FieldHandle(raw, PhantomData)
    }
}

// Shallow-method buffer accessors.  Methods take (slot, field) and dispatch
// to the FFI layer.  The type system enforces that `field` belongs to the
// same buffer type as the impl block.

impl MainBuffer {
    #[inline(always)]
    pub fn get_u32(&self, slot: Slot, field: FieldHandle<MainBuffer>) -> u32 {
        unsafe { ffi::blyt32_state_get_u32(slot.0, field.0) }
    }

    #[inline(always)]
    pub fn set_u32(&self, slot: Slot, field: FieldHandle<MainBuffer>, val: u32) {
        unsafe { ffi::blyt32_state_set_u32(slot.0, field.0, val) }
    }
}

// EnemiesBuffer has the same shallow-method API.  This is the second buffer
// type used only by guard_wrong_buffer; in production there would be many
// such buffer types generated by the packer.
impl EnemiesBuffer {
    #[inline(always)]
    pub fn get_u32(&self, slot: Slot, field: FieldHandle<EnemiesBuffer>) -> u32 {
        unsafe { ffi::blyt32_state_get_u32(slot.0, field.0) }
    }

    #[inline(always)]
    pub fn set_u32(&self, slot: Slot, field: FieldHandle<EnemiesBuffer>, val: u32) {
        unsafe { ffi::blyt32_state_set_u32(slot.0, field.0, val) }
    }
}
